homeassistant:
  name: Appart
  latitude: 48.873696
  longitude: 2.233231
  elevation: 34
  time_zone: Europe/Paris
  customize: !include customize.yaml
  unit_system: metric

http:
  api_password: Losc123@

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

####################################################
#                                                  #
#                     Includes             #
#                                                  #
####################################################

###  Devices  ###
device_tracker: !include devices/device_trackers.yaml
media_player: !include devices/media_players.yaml
sensor: !include devices/sensors.yaml
binary_sensor: !include devices/binary_sensors.yaml
switch: !include devices/switches.yaml
automation: !include automations.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
notify: !include notify.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
#templated_shell_command: !include templated_shell_command.yaml
weblink: !include weblink.yaml

###  Custom  ###
panel_iframe: !include panel_iframe.yaml


####################################################
#                                                  #
#                     Enables             #
#                                                  #
####################################################
recorder:
  purge_interval: 2
  purge_keep_days: 7
logger:
  default: warning
frontend:
history:
  exclude:
    domains:
      - sensor
      - weblink
      - input_select
      - input_number
      - input_boolean
discovery:
sun:
logbook:
updater:
config:

