- platform: template
  sensors:
    door:
      value_template: "{{ states.sensor.vision_zd2102_eu_doorwindow_sensor_access_control_3_9.state == '22' }}"
      sensor_class: opening
      entity_id: sensor.vision_zd2102_eu_doorwindow_sensor_access_control_3_0
