#Forecast
- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - humidity
    - fog
    - cloudiness
#Time & Date
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
- platform: worldclock
  time_zone: America/Mexico_City
  name: Mexico
- platform: worldclock
  time_zone: America/Argentina/Buenos_Aires
  name: Buenos Aires
- platform: worldclock
  time_zone: America/Sao_Paulo
  name: Sao Paulo
#System
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: since_last_boot
- platform: version
#Speedtest
- platform: speedtest
  minute: 30
  hour: 0
  monitored_conditions:
    - ping
    - download
    - upload
#Travel Time
- platform: google_travel_time
  api_key: AIzaSyBAbs84jl4Ac1cxgfKovwKlQ7Ai7rvRy4k
  origin: 16 Rue Salomon de Rothschild, Suresnes, France
  destination: 250 Route de l'Empereur, Rueil-Malmaison, France
- platform: google_travel_time
  api_key: AIzaSyBAbs84jl4Ac1cxgfKovwKlQ7Ai7rvRy4k
  origin: 16 Rue Salomon de Rothschild, Suresnes, France
  destination: 9 rue Xavier de Maistre, Rueil-Malmaison, France
- platform: google_travel_time
  api_key: AIzaSyBAbs84jl4Ac1cxgfKovwKlQ7Ai7rvRy4k
  origin: 16 Rue Salomon de Rothschild, Suresnes, France
  destination: 298 Avenue Napoleon Bonaparte, Rueil-Malmaison, France
#Command Line
- platform: command_line
  command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
  name: Latest HA release
#Time
- platform: template
  sensors:
    alarm_time:
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmhour") | int, states("input_number.alarmminutes") | int) }}'
    time_paris:
      value_template: '{{ now().strftime("%-H") }}:{{ now().strftime("%-M") }}'
#Sonarr
- platform: sonarr
  api_key: 905993e661ec4c9b85bf3dd3a1136d64
  host: 192.168.0.122
  port: 8989
  monitored_conditions:
    - upcoming
  days: 5

